name: GitHub Action for CV deployment
run-name: Linting and deploying the CV to GitHub Pages
on:
  [push]
  # push:
  #   branches:
  #     - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
  # build :
  # this CV is an old stuff , some refactoring to be able to run "npm run build" would be nice
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy CV on server
        run: echo "to do"
        # run an ansible playbook to deploy the ./CV on the server