name: GitHub Action for CV deployment
run-name: Linting and deploying the CV to GitHub Pages
on: [push]
  # push:
  #   branches:
  #     - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
          only_changed: True